name: Auto merge PRs at 23:00 KST

on:
  schedule:
    - cron: "0 14 * * *" # UTC 14 = KST 23ì‹œ
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-24.04
    steps:
      - name: Auto-merge pull requests
        uses: pascalgn/automerge-action@v0.16.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_METHOD: squash
          MERGE_LABELS: ""
          MERGE_FILTER_AUTHOR: ""
          MERGE_FORKS: true
          MERGE_DELETE_BRANCH: false
